spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_system
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: 8SI96vZ/O0rHTVojpn2faer67NkdYrxfdes8VL11UcU=
logging:
  level:
    org:
      springframework:
        web:
          socket: DEBUG
        messaging: DEBUG
api:
  key: 29b420e9-0c27-4a41-8e2d-51587f8e8755